name: Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install openai
      - name: Get PR title and description
        id: pr
        uses: peter-evans/get-pull-request@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate code review
        id: review
        uses: openai/gpt-2@v1
        with:
          prompt: |
            Please review the following code changes:

            ${steps.pr.outputs.title}

            ${steps.pr.outputs.body}

            Review:
          max-tokens: 100
          temperature: 0.7
          api-key: ${{ secrets.GPT_SECRET_KEY }}
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: ${{ steps.review.outputs.text }}
          path: review.md
          repo-token: ${{ secrets.GITHUB_TOKEN }}
