name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generate code review comment
        uses: openai/language@v1
        id: chat
        with:
          engine: "text-davinci-002"
          prompt: |
            Please review the code changes in this pull request and leave a comment with any suggestions or feedback.
          secret: ${{ secrets.GPT_SECRET_KEY }}

      - name: Store code review comment
        run: |
          echo "${{ steps.chat.outputs.generated_text }}" > comment.txt

      - name: Leave code review comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const comment = fs.readFileSync('comment.txt', 'utf8');
            const { data } = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });

