name: Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install OpenAI Python package
        run: |
          pip install openai

      - name: Generate review comment
        id: review
        run: |
          comment=$(openai.Completion.create(engine="text-davinci-002",prompt="Please review the changes in the pull request and provide feedback. Changes:\n\n" + "$(git diff --name-only "${{ github.base_ref }}" "${{ github.head_ref }}")",max_tokens=1024,n=1,stop=None,temperature=0.5)["choices"][0]["text"]) \
          echo "::set-output name=comment::$comment"

      - name: Leave review comment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"${{ steps.review.outputs.comment }}\"}" \
            "${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments"
